#!/bin/bash

# Create the destination directory if it doesn't exist
if [ ! -d "/tmp/u" ]; then
  mkdir /tmp/u
fi

for file in *; do
 
  first_letter=$(echo "$file" | cut -c1)
  if [ "$first_letter" == "${first_letter^^}" ]; then
   
    mv "$file" /tmp/u/
    echo "Moved $file to /tmp/u/"
  fi
done
